#!/usr/bin/env bash
# Script that displays Holberton school 10 times but in the 9th iteration print hi
i=0
while [ $i -lt 10 ]
do
	if [[ $i -eq 9 ]]
	then
		echo "Hi"
	fi
	echo "Best School"
	(( i++ ))
done
